wallet: "../../frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nyan_contract: "77a7c4e6f9307e5ce55136daa92ce5cb4621f8be"
storage_node: "localhost:8080"
storage_container: "5cAiMSCNogpdwJ6fi2iEcYA4Sj3qm3Y9xD3gkmWHwKBR"
listen_address: ":5555"