wallet: "../../frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nft_contract: "f8663ed5995b8eaf5c60405188ff77f89f51bb08"
auction_contract: "47653fc3c65ffbaa777763783b5a9a739a9e9840"
storage_node: "localhost:8080"
storage_container: "69aHG2Xk6opKE72o6K2up6okLh7iDMZww2tYjdXpvrSd"
listen_address: ":5555"
product_api_url: "https://dummyjson.com/products/"