wallet: "../../frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nft_contract: "f8663ed5995b8eaf5c60405188ff77f89f51bb08"
auction_contract: "f272e2013ceca2059d34f87708abbc7c39488b16"
storage_node: "localhost:8080"
storage_container: "J44JvyNvUzkPneC4Wn7HdHwixcSzxaTZGDHgg2T2NN83"
listen_address: ":5555"
product_api_url: "https://dummyjson.com/products/"