wallet: "../../frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nft_contract: "01b7097b6457ac1b2316abcb1ae0501090684611"
auction_contract: "87ab16fce8b7faa8b1d626f75dda8a7d94ca100c"
storage_node: "localhost:8080"
storage_container: "J44JvyNvUzkPneC4Wn7HdHwixcSzxaTZGDHgg2T2NN83"
listen_address: ":5555"
product_api_url: "https://dummyjson.com/products/"