wallet: "../../frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nns_contract: "8477fcff838587103b4d008a198a4a0c3a62a5b2"
storage_node: "localhost:8080"
storage_container: "Ffe2YcTfQiDhd3aUpBr3UX3Vh97F97Yd2Dz4ZemXsJaR"
listen_address: ":5555"
product_api_url: "https://dummyjson.com/products/"